/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package me.msvasilets.plugin

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'me.msvasilets.plugin.greeting' plugin.
 */
class ReleaseGradlePluginPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("me.msvasilets.plugin.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
